$lang{SERVICE_NAME}='Service name';
$lang{SECTION}='Section';
$lang{SERVICE}='Service';
$lang{SECTION_ICON}='Section icon';
$lang{DESCRIPTION}='Description';
$lang{ADDRESS}='Address';
$lang{AVR_TIME}='Avr time';
$lang{IMAGE}='Image';
$lang{ADD_SECTION}='Add section';
$lang{ADD_INFO}='Add info';
$lang{ICON}='Icon(Font Awesome)'; 
$lang{TIME_START}='Start time';
$lang{TIME_FINISH}='Time finish';
$lang{LAT}='Latitude';
$lang{LNG}='Longtitude';
$lang{START_DATE}='Start date(y-m-d)';
$lang{FINISH_DATE}='Finish date(y-m-d)';
$lang{HEAD_COLOR}='Header color';
$lang{OFFER}='Offer';
$lang{GO_BACK}='Go back';

1;