#!perl

use strict;
use warnings FATAL => 'all';
use Data::Dumper;
use Abills::Base qw(_bp);
use Organizer::db::Organizer;
our ($db, $admin, %info, %conf, %lang, $html,);

my $Organizer = Organizer::db::Organizer->new($db, $admin, \%conf);
#**********************************************************
=head2 service_price_add() - Add headers and items to DB 

  Arguments:
     
  Returns:
    true
=cut
#**********************************************************
sub organizer_add {
  my $show_template1 = $FORM{section_form} || 0;
  $Organizer->{ACTION}     = 'add_section';
  $Organizer->{LNG_ACTION} = $lang{ADD};

  if ($FORM{add_section}) {
    $Organizer->section_add({%FORM});
    if (!$Organizer->{errno}) {
      $html->message('info', $lang{INFO}, $lang{ADDED});
    }
  }
  $html->tpl_show(_include('organizer_add', 'Organizer'), $Organizer);


   my $show_template2 = $FORM{info_form} || 0;
  $Organizer->{ACTION}     = 'add';
  $Organizer->{LNG_ACTION} = $lang{ADD};

  if ($FORM{add}) {
    $Organizer->info_add({%FORM});
    if (!$Organizer->{errno}) {
      $html->message('info', $lang{INFO}, $lang{ADDED});
    }
  }
   my $section_select = $html->form_select(
    'SECTION_ID',
    {
      SELECTED => $FORM{SECTION_ID} || q{},
      SEL_LIST  => $Organizer->get_section({ COLS_NAME => 1 }),
      SEL_KEY   => 'id',
      SEL_VALUE => 'section_name'
    }
  );
   $html->tpl_show(_include('organizer_add_info', 'Organizer'), { 
    SECTION_SELECT => $section_select, %$Organizer});
  
  return 1;
}

1;